### PR TITLE
security updates + volantisg

### PR DESCRIPTION
**Pull request by Haul22**
Created volantisg (Nexus 9 LTE).
Added April 2016 factory images for angler, bullhead, hammerhead, razorg, and shamu.

### CODE REVIEW

**Comment by Haul22** [comment]
Google has pulled the factory images for fugu, volantis, and razor, so those obviously can't be added yet.

**Comment by phhusson** [comment]
Thanks (You've seen the new checkNexus.sh script?)

**Comment by Haul22** [comment]
No, I haven't seen it.  Sorry, I can't find it and don't know where to look.  What is it and where can I find it?

**Comment by phhusson** [comment]
Erf, I forgot to push it...
https://github.com/phhusson/super-bootimg/blob/master/checkNexus.sh

**Comment by Haul22** [comment]
Wow, that script looks pretty awesome!

**Pull request merged**
