### PR TITLE
Hidesu improvements (part 2)

### PR DESCRIPTION
**Pull request by DavisNT**
- Unmount anything mounted **under** _/system_. This should be the proper alternative to bind-mounting _/system_ over _/system_.
- Rise priority to give advantage in race conditions.
- Use SIGSTOP and SIGCONT on app processes to give advantage in race conditions. Idea taken from Magiskhide (by John Wu (@topjohnwu)).
- Minor fixes and optimizations.

### CODE REVIEW

**Comment by DavisNT** [comment]
Next step will be rewriting the shellscript in C to:

1. Give advantage in on-boot race condition by improving performance.
2. Remove dependency on shell/tools (toybox/busybox).

**Comment by DavisNT** [comment]
The commit 36e918632436e5fa5dba3af1bde6e1a47e778a0d adds functionality that was implemented in `hidesu-start.sh` to `hidesu` and removes the shellscript. 

@phhusson  Can you please review and merge?

**Comment by phhusson** [comment]
I've rewritten history this way:
https://github.com/phhusson/super-bootimg/commit/9448575259961eda5bd146155963102b46f26291
This look good to you?

**Comment by DavisNT** [comment]
Yes, 9448575259961eda5bd146155963102b46f26291 looks good! :slightly_smiling_face:

**Comment by DavisNT** [comment]
Looks like there is a bug - device gets randomly unrooted (till next reboot) at rare occasions. 
Will push a fix soon.

**Comment by DavisNT** [comment]
Just made a2aa239e2147102ce99c33aaf59e7e71a31b88c0.
It has all the changes in single commit. @phhusson Can you please review and merge it?

**Comment by DavisNT** [comment]
The previous change has been time tested for around 9 days now (with no random unrootings observed). 
I have made a bit updated commit 2a33198678e5b68a5d4f34c31c9e89e0cdbef11e. 
This commit includes: 

- All the previous changes.
- Support for full 32-bit (unsigned int/unsigned long on NDK 32-bit ARM) PIDs.
- Fixed constant buffer size in prepareZygoteNs().
- Some minor cosmetic fixes.

**Comment by DavisNT** [comment]
All changes in this Pull Request are put in a single commit as Pull Request #62

**Pull request closed without merging**
