### PR TITLE
Improve hidesu

### PR DESCRIPTION
**Pull request by DavisNT**
Idea taken from Magiskhide (by John Wu (@topjohnwu)), implementation is
different. 

Probably this will need testing on different devices. 
@phhusson May be you could release a new beta after merging this?

### CODE REVIEW

**Comment by phhusson** [comment]
Your change is quite intrusive, while I'd like to have hidesu as little intrusive as possible.
Would you have some test case? I assume that's for SafetyNet?

In my understanding, the difference between my current hidesu, and the one you're doing, is that with mine, the process would have to look at /proc/mountinfo to detect something's wrong. With yours, it has to see if a "/root" folder exists
It seems to me, the update to the root-detector code would be a one-liner.

One possibility to make your change much more harder to detect would be to use a folder which can't be looked at by any non-root process, for instance by keeping su in /sbin/su, BUT /sbin keeps original 0700, and reusing your tmpfs trick to have /sbin readable by everyone.
(if /sbin is readable on the ROM, that's more problematic, we would have to hide su somewhere else... perhaps /dev? /init? /init.xxx.rc?)
Also, I recommend to also unnmount /dev/sbin.tmp in hidesu, else the trick is still detectable through mountinfo

**Comment by DavisNT** [comment]
The _/root_ folder is present by default (at least on some ROMs) and readable only by _root_ (so binary detection from app should not be possible 😄). Scripts only ensure _/root_ is not accessible on the particular ROM (I am not whether it is present on all ROMs and whether it is 0700 on all ROMs). 
On my ROM _/sbin_ has 0750 (owned by root:root) by default (so it should be inaccessible from apps). We could actually always keep the binaries in _/sbin_ and:

1. ensure that _/sbin_ has 0750 (and make the tmpfs mount) in case of hidesu
2. ensure it has 0755 in case not hiding su

_/dev/sbin.tmp_ is already unmounted and removed in _hidesu-start.sh_

**Comment by phhusson** [comment]
It's easier to read if the commits are squashed ;)

Looks overall good.
Do you think that moving the chmod 0750 /sbin to hidesu-start.sh could be problematic?
(this way, all hidesu-specific dynamic setup is in the same place)

I'm a bit worried about the
-       res = mount("/system", "/system", "bind", MS_BIND, "");
This means that mount bind will now be detected again.
Did you need this change?

Also, I'd still like to know what is your test case? SafetyNet? basic integrity or cts? Some other app?

**Comment by DavisNT** [comment]
Moving `chmod 0750 /sbin` would need remounting _/_ as _rw_ and afterwards there might be problems remounting it back as _ro_ (plus I think that both permission adjustments on _/sbin_ should be kept in one place; currently _hidesu-start.sh_ is used only for copying _/sbin_ to tmpfs and mounting it). Regarding mounting, now tmpfs is remounted _ro_ before bind-mounting on _/sbin_ (to prevent issues with remount _ro_). 

The line `res = mount("/system", "/system", "bind", MS_BIND, "");` was removed. 
Now _hidesu_ does only a single operation - unmounts _/sbin_ tmpfs.

Regarding testing - you have good intuition. 😉

**Comment by phhusson** [comment]
My question about the mount("/system", ...) is why has it been removed :)
The aim of mount("/system"...); is that, when you did mount -o bind /data/tmp/hosts /system/etc/hosts, then when the application access /system/etc/hosts, it sees real, original, /system/etc/hosts, instead of /data/tmp/hosts.
Hence I believe it is useful. If this trick is detected by SafetyNet, then I guess no mount -o bind works at the moment?
Mouting a fake mountinfo should fix that

Ok for hidesu-specific /sbin permission and remounting ro earlier.

**Comment by phhusson** [comment]
You tested it? It's still okay with it there?

**Comment by DavisNT** [comment]
It works on my machine.
But this is a real oneliner to detect...

**Comment by phhusson** [comment]
Well, ok, let's make a first step without it.

Next step will be to re-enable it, and faking mountinfo.

**Comment by phhusson** [comment]
Squashed without mount bind on /system:
https://github.com/phhusson/super-bootimg/commit/2ff7d04369929413898ffb333895219f8742df43

Thanks!

**Comment by phhusson** [comment]
Could you confirm that http://phhusson.free.fr/superuser-r315.zip works for you?

**Comment by DavisNT** [comment]
That file is working for me 😄 👍

**Pull request closed without merging**
