### PR TITLE
Update FP2 to 1.7.0

### PR DESCRIPTION
**Pull request by retsifp**
Fairphone just released 1.7.0 ([Release Notes](https://fairphone.zendesk.com/hc/en-us/articles/208342503))

Unfortunately, I changed the chmod of `download.sh` to 755 (to execute it), is this a problem? :wink:

### CODE REVIEW

**Comment by phhusson** [comment]
No problem with execute bit, but could you squash the commits?

**Comment by retsifp** [comment]
Great! I didn't know this is possible! Thanks a lot! :+1:

**Comment by retsifp** [comment]
Will your buildserver update it's builds? :wink:

**Comment by phhusson** [comment]
Yup. I've started it. If there is no fail it should generate it soon.

**Pull request merged**
